# This workflow will build a Java project

name: NookCity build

on:
  push:
    branches: [ master ]
jobs:
  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Setting up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: |
          chmod +x gradlew
          ./gradlew shadowJar
          mkdir staging && cp build/libs/*.jar staging
      - name: Upload the jar
        uses: actions/upload-artifact@v4
        with:
          name: NookCity
          path: staging